from mongoengine import Document, StringField, IntField, DateField, EmailField, ImageField, BinaryField

class Profil(Document):
    cartCin = StringField(max_length=20, required=True, verbose_name='Numéro de carte d\'identité nationale')
    firstName = StringField( max_length=150, verbose_name='Prénom')
    lastName = StringField( max_length=150, verbose_name='Nom')
    prenom_arabe = StringField( max_length=150, verbose_name='الاسم الأول')
    nomArabe = StringField( max_length=150, verbose_name='اللقب')
    lieuNaissanceArabe = StringField(max_length=100,  verbose_name='مكان الولادة')
    adresseArabe = StringField( verbose_name='العنوان')
    delegationArabe = StringField(max_length=100, verbose_name='المعتمدية ')
    dateDeDelivrance = DateField( null=True, verbose_name='Date de délivrance')
    genre = StringField(max_length=10, verbose_name='Genre')
    etatCivil = StringField(max_length=20,  verbose_name='État civil')
    nationalite = StringField(max_length=100,  verbose_name='Nationalité')
    dateNaissance = DateField( null=True, verbose_name='Date de naissance')
    lieuNaissance = StringField(max_length=100, verbose_name='Lieu de naissance')
    adresse = StringField( verbose_name='Adresse')
    gouvernorat = StringField(max_length=100,  verbose_name='Gouvernorat')
    delegation = StringField(max_length=100,verbose_name='Délégation')
    codePostal = StringField(max_length=10,  verbose_name='Code postal')
    email = EmailField(unique=True)
    phoneNumber = IntField(default=0)
    image = StringField(blank=True, default='') 